### ISSUE TITLE
what about to replace jxbrowser with jcef

### ISSUE THREAD

**Issue by xiaoyifang** [yzyray/lizzieyzy#109]
https://github.com/jcefmaven/jcefmaven

**Comment by yzyray** [comment]
I'm not sure,JCEF seems need to be supported by local libs and can not compile once and used in both windows macos and linux.

**Comment by xiaoyifang** [comment]
they provide as maven repository .
`<dependency>
    <groupId>me.friwi</groupId>
    <artifactId>jcefmaven</artifactId>
    <version>95.7.14.4</version>
</dependency>`
which means there is no need to compile.but I'm also not sure.

**Comment by yzyray** [comment]
I have tried the maven repository ,and got some error
```Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no chrome_elf in java.library.path: [D:\java-11-openjdk-11.0.13.8-1.windows.ojdkbuild.x86_64\bin, C:\WINDOWS\Sun\Java\bin, C:\WINDOWS\system32, C:\WINDOWS, C:/Users/yzy/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955/jre/bin/server, C:/Users/yzy/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955/jre/bin, C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Users\yzy\AppData\Local\Microsoft\WindowsApps, ., C:\Users\yzy\Desktop, ., .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.cef.SystemBootstrap$1.loadLibrary(SystemBootstrap.java:24)
	at org.cef.SystemBootstrap.loadLibrary(SystemBootstrap.java:36)
	at org.cef.CefApp.<init>(CefApp.java:145)
	at org.cef.CefApp.getInstance(CefApp.java:221)
	at org.cef.CefApp.getInstance(CefApp.java:208)
	at featurecat.lizzie.gui.LizzieFrame.OfficalDemo(LizzieFrame.java:8892)
	at featurecat.lizzie.gui.LizzieFrame.bowser(LizzieFrame.java:9004)
	at featurecat.lizzie.gui.BottomToolbar$14.actionPerformed(BottomToolbar.java:712)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
```
And I searched how to use jcef in maven and got this [answer](https://stackoverflow.com/questions/21192279/how-to-integrate-chromium-embedded-framework-cef-with-java)
Looks like need complie and loading dlls  in windows

**Comment by xiaoyifang** [comment]
then we have to keep as it is   for now   ..:-)

**Comment by xiaoyifang** [comment]
windows下是可以正常的。需要包含

···
		<dependency>
			<groupId>me.friwi</groupId>
			<artifactId>jcefmaven</artifactId>
			<version>95.7.14.4</version>
		</dependency>
		<dependency>
			<groupId>me.friwi</groupId>
			<artifactId>jcef-natives-windows-amd64</artifactId>
			<version>jcef-a51ff7f+cef-95.7.14+g9f72f35+chromium-95.0.4638.69</version>
		</dependency>
···
不过不同的平台需要包含不同的native maven包

**Comment by yzyray** [comment]
确实可以,我之前少加第二部分的dependency.后续我再试试linux的,如果OK的话就太好了,替换掉jxbrowser

**Comment by yzyray** [comment]
我试了下还是有点问题,无论是参考这个[例子](https://github.com/jcefmaven/jcefsampleapp/blob/95.7.14.4/src/main/java/me/friwi/jcefsampleapp/MainFrame.java)
还是用官方的[release](https://github.com/jcefmaven/jcefsampleapp/releases/tag/95.7.14.4)
打开google然后点击里面的链接是OK的,但是打开[弈客直播](https://home.yikeweiqi.com/#/live),点击某一局后就是空白....
![image](https://user-images.githubusercontent.com/49384584/151683560-70bb8a14-1337-4b51-aa68-81fec5605495.png)

**Comment by xiaoyifang** [comment]
是不是需要开启某些setting配置

**Comment by yzyray** [comment]
确实很奇怪 不应该这么简单的链接跳转都不行...百度首页跳转新闻都不行,但是谷歌就都是好的

**Comment by yzyray** [comment]
应该可以了,测试了windows-amd64和linux-amd64的package都可以用,似乎就算系统对不上也会自动下载正确的版本.
