### ISSUE TITLE
java.lang.NullPointerException on Startup (macOS)

### ISSUE THREAD

**Issue by neolee** [yzyray/lizzieyzy#200]
Latest release, running on macOS 12.5, OpenJDK 17, reporting on startup:

```
❯ java -jar lizzie-yzy2.5.1-shaded.jar
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.awt.Toolkit.getDesktopProperty(String)" is null
	at featurecat.lizzie.Config.<init>(Config.java:999)
	at featurecat.lizzie.Lizzie.main(Lizzie.java:59)
java version:17.0.4
```

Seems missing some config properties, not critical but still wanna fix that :)

**Comment by yzyray** [comment]
Yes,it should be a windows only message.
