### ISSUE TITLE
linux java版本无法使用奕客同步

### ISSUE THREAD

**Issue by matolv** [yzyray/lizzieyzy#216]
```
INFO: EXTRACTING |> In progress...
**java.io.EOFException: Unexpected end of ZLIB input stream**
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
	at org.apache.commons.compress.utils.CountingInputStream.read(CountingInputStream.java:56)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:304)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:738)
	at me.friwi.jcefmaven.impl.step.extract.TarGzExtractor.extractTarGZ(TarGzExtractor.java:47)
	at me.friwi.jcefmaven.CefAppBuilder.build(CefAppBuilder.java:212)
	at featurecat.lizzie.gui.BrowserFrame.<init>(BrowserFrame.java:101)
	at featurecat.lizzie.gui.LizzieFrame$67.run(LizzieFrame.java:8731)
```
参考stackflow可能解决方法为：https://stackoverflow.com/questions/24531089/exception-unexpected-end-of-zlib-input-stream

**Comment by matolv** [comment]
已解决。
问题：在debian 11 openjdk 11.0.16 安装解压失败。
解决方法：在centos 8s/RHEL 8 openjdk 1.8.5 下载解压安装成功，替换jcef-bundle文件夹中内容即可，还望作者下次发布时增加一个整合包选项。
