### ISSUE TITLE
Problems when changing fonts 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#72]
I translated Lizzieyzy into Japanese, but the characters were a little hard to see, so I changed the font to "Yu Gothic UI" used in Windows 10. (Each item in the upper menu and pull-down menu) 
Specifically, I changed each item of DisplayStrings_ja_JP.properties as follows. 
`Menu.fileMenu=<html><span style="font-family: Yu Gothic UI;font-size: 110%;">\u30D5\u30A1\u30A4\u30EB`

There I noticed a bug. In the game → engine game, even if I used the option to load SGF, an error message appeared and I could not proceed. If you load an SGF and then try to start the game, you will be asked to load at least one SGF. 
The error log is shown below. 

LastConsoleLogs_yzy2.4.6.1.txt

>2021-12-20-11:42:00
java version:14.0.1
engine process ended.

LastGtpLogs_yzy2.4.6.1.txt

>2021-12-20 11:42:02+0900: GTP Engine starting...
2021-12-20 11:42:02+0900: KataGo v1.10.0
2021-12-20 11:42:02+0900: Using Japanese rules initially, unless GTP/GUI overrides this
2021-12-20 11:42:02+0900: Using 16 CPU thread(s) for search
2021-12-20 11:42:02+0900: nnRandSeed0 = 1825351923542001681
2021-12-20 11:42:02+0900: After dedups: nnModelFile0 = weights\kata1-b40c256-s10499183872-d2559211369.bin.gz useFP16 auto useNHWC auto
2021-12-20 11:42:02+0900: Initializing neural net buffer to be size 19 * 19 exactly
2021-12-20 11:42:03+0900: TensorRT backend thread 0: Found GPU NVIDIA GeForce RTX 2060 memory 6442123264 compute capability major 7 minor 5
2021-12-20 11:42:03+0900: TensorRT backend thread 0: Initializing (may take a long time)
2021-12-20 11:42:05+0900: Using existing cache at KataGoData/trtcache/kata1-b40c256-s10499183872-d2559211369_gpu_75_19x19-exact_batch16_fp16
2021-12-20 11:42:06+0900: TensorRT backend thread 0: Model version 10 useFP16 = true
2021-12-20 11:42:06+0900: TensorRT backend thread 0: Model name: kata1-b40c256-s10499183872-d2559211369
2021-12-20 11:42:06+0900: Loaded neural net with nnXLen 19 nnYLen 19
2021-12-20 11:42:06+0900: Initializing board with boardXSize 19 boardYSize 19
2021-12-20 11:42:06+0900: Loaded config katago_configs\default_gtp.cfg
2021-12-20 11:42:06+0900: Loaded model weights\kata1-b40c256-s10499183872-d2559211369.bin.gz
2021-12-20 11:42:06+0900: Model name: kata1-b40c256-s10499183872-d2559211369
2021-12-20 11:42:06+0900: GTP ready, beginning main protocol loop
 =
 = KataGoCustom

LastErrorLogs_yzy2.4.6.1.txt

>2021-12-20-11:42:00
Exception in thread "AWT-EventQueue-0" java.util.UnknownFormatConversionException: Conversion = ';'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2708)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:3302)
	at featurecat.lizzie.gui.LizzieFrame.setPlayers(LizzieFrame.java:7236)
	at featurecat.lizzie.rules.SGFParser.parse(SGFParser.java:781)
	at featurecat.lizzie.rules.SGFParser.load(SGFParser.java:75)
	at featurecat.lizzie.gui.LizzieFrame.loadFile(LizzieFrame.java:3511)
	at featurecat.lizzie.gui.LizzieFrame.openSgfStart(LizzieFrame.java:3420)
	at featurecat.lizzie.gui.NewEngineGameDialog$8.actionPerformed(NewEngineGameDialog.java:808)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1717)
	at java.desktop/java.awt.Component.setVisible(Component.java:1664)
	at java.desktop/java.awt.Window.setVisible(Window.java:1023)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at featurecat.lizzie.gui.LizzieFrame.startEngineGameDialog(LizzieFrame.java:9258)
	at featurecat.lizzie.gui.Menu$120.actionPerformed(Menu.java:2588)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by yzyray** [comment]
Menu.fileMenu=<html><span style="font-family: Yu Gothic UI;font-size: 110%;">\u30D5\u30A1\u30A4\u30EB
This is strange,the right part after `=` should be only characters,the "<html><span style="font-family: Yu Gothic UI;font-size: 110%;">" is html language will not be supported and need to be deleted.

>By the way, I noticed one thing. In Lizzieyzy 2.4.6.1, it was not possible to enter the "field to specify the winning percentage of >random move" in the detailed setting field of the game between engines, but it became possible if the font of "WinRate >above best" was changed to Yu Gothic UI. rice field.
Yes, this is a bug and should already be fixed in 2.4.7.

**Comment by hope366** [comment]
`<html><span style="font-family: Yu Gothic UI;">`I don't want to remove it if possible because using it will clean up the font, but isn't it desirable to use it?

**Comment by yzyray** [comment]
>`<html><span style="font-family: Yu Gothic UI;">`I don't want to remove it if possible because using it will clean up the font, >but isn't it desirable to use it?

It will only works in specific widget like JLabel,I dont think the JMenu can use this way to change font...

**Comment by hope366** [comment]
For comparison, I just reverted the menu "File" and its pull-down menu.
The top is the one using Yu Gothic UI, and the bottom is the normal one. In Yu Gothic UI, the space between characters is narrowed, and it is possible to place many characters within a narrower range. 
![無題](https://user-images.githubusercontent.com/63999713/147428164-80ea91c8-219d-49f6-a2ec-98cfae724d70.png)
![無題1](https://user-images.githubusercontent.com/63999713/147428174-3a6932d0-3cea-4da5-a9d0-53928f2001cd.png)

**Comment by yzyray** [comment]
I added a item Menu.baseMenu.fontName for set the font.

**Comment by hope366** [comment]
https://github.com/yzyray/lizzieyzy/commit/c15f43489545474d9a0060a09ae1ab7cabd04078 I tested it. 
Could not find the display for "Dialog.plain" or "Yu Gothic UI". In what part of the GUI do these appear? 
What is the specific effect of this change?

**Comment by yzyray** [comment]
![image](https://user-images.githubusercontent.com/49384584/147543085-c2cc9779-4868-41b3-929b-21b289fdf156.png)

This part of menu's font will be changed according to `Menu.baseMenu.fontName` item in DisplayStrings

**Comment by hope366** [comment]
Thank you for letting me know.
I have created DisplayStrings_ja_JP.properties with Yu Gothic UI applied to almost all items, not just menus. Shouldn't this be submitted as a pull request?

**Comment by yzyray** [comment]
You can compare your DisplayStrings_ja_JP.properties  with my 2.4.7 branch,if not same you can submit a pr to 2.4.7 branch.

**Comment by hope366** [comment]
I was hesitant to publicize because I was told that the Yu Gothic UI could not be used.
If it's okay, I'll submit it as soon as it's organized to some extent.
